### ISSUE TITLE
Optimal treedepth for Exact instances

### ISSUE THREAD

**Issue by aditya95sriram** [lkowalik/Treedepth-PACE-2020-instances#1]
It would be really helpful to also publish the (known) values for the optimal treedepth for the exact instances. I suppose this could be added to the `exact.csv` file.

**Comment by lkowalik** [comment]
Dear Aditya,

Both exact.csv and heur.csv files are now updated with treedepth values (in
case of heur.csv these are just upper bounds, in case of exact.csv these
are almost surely optimal values).

Sorry it took so long: I had to find two hours of free time to complete it.
Thanks for your interest -- this information was missing indeed, and should
have been added.

Best
Lukasz

śr., 28 paź 2020 o 16:18 Aditya Sriram <notifications@github.com>
napisał(a):

**Comment by aditya95sriram** [comment]
Thanks a lot! Your effort is much appreciated
